### PR TITLE
Bit of a cleanup?

### PR DESCRIPTION
**Pull request by Ickerday**
So I liked that it's basically TegraSmashGUI for macOS and took the time to make the code a bit neater. 
Let me know if there's something wrong with it and feel free to merge it in if you'd like!
Oh, and definitely try to break it.

### CODE REVIEW

**Comment by SuperOkazaki** [comment]
It looks great, but I'm not sure how I feel about advising the user to use a virtualenv, which I haven't myself. At that point it would be another thing for me to help debug on my GBATemp thread when something goes wrong.

**Comment by SuperOkazaki** [comment]
Hmm, it seems that the `gui.py` is nonfunctioning.

I did a clean git clone and I receive this error
`Traceback (most recent call last):
  File "gui.py", line 53, in <module>
    tk.messagebox.showerror(
AttributeError: module 'tkinter' has no attribute 'messagebox'`

Whereas I do not with the old version. If I can debug this error and fix it, I will merge the .py changes. For now I will merge the other files.

Thank you for your contribution!

**Review by SuperOkazaki — DISMISSED** [review]

**Comment by Ickerday** [comment]
I'll have a look when I get home, I wasn't too sure about that import myself. Good thing that you broke it - we'll have less work on our hands. :P

**Comment by Ickerday** [comment]
About virtualenv - IMHO having a separate environment for the program to work in could actually help in debugging, but I'd still leave it as an option for those who want it, rather than adopting it as a preferred method. 
We could also think of py2app, but I don't have any experience in that. 

Would you like some help on GBAtemp as well?

**Comment by SuperOkazaki** [comment]
Let me look into how virtualenv works and then I can make a decision about that myself, whether I want to have it listed in the readme. As for the thread, [you're welcome to help out](https://gbatemp.net/threads/tool-fusee-gelee-launcher-for-macos.502075/). It's been forever since I've collaborated on git so I forgot how to cherry-pick commits from a PR. So until the gui.py gets worked out I will leave the PR as it is. Thank you for your contribution, and hopefully we can get this properly merged.

**Comment by Ickerday** [comment]
Ok, sounds good!

**Comment by Ickerday** [comment]
Pushed some fixes. I took care to test the code more properly now! Lemme know if it works on your machine.

**Comment by SuperOkazaki** [comment]
Good stuff, works great now. I'm a bit iffy still on virtualenv, at least until I get more experience with it, but the python code cleanup works perfectly. Thank you for your contribution!

**Comment by SuperOkazaki** [comment]
Huh, interestingly enough, the launcher now works through a USB hub, whereas before it did not, at least for me. Likely a coincidence but an odd one nonetheless.

**Comment by Ickerday** [comment]
Yeah `virtualenv` and all those other tools can be mind-boggling at first. The benefits are awesome though. 
Here's my general workflow: https://docs.python-guide.org/dev/virtualenvs/#lower-level-virtualenv

As for the USB hub bit - that's weird, but I'd wager we had nothing to do with it - we only changed our part, `fusee-launcher.py` was unchanged.

**Pull request merged**
